%% Preliminaries

cd ~/Repositories/MOGADOR
run params.m

%% Initialize Ouput Parameters

o = cell(p.maxGenerations,1);
gen = struct();

%% Simulate Objective Variables 

p.objectiveVars = simObjectivesFnc(...
    p.objectiveCount,...
    p.objectiveSimulationMean,...
	p.objectiveSimulationRange,...
	p.gridMask     );

%% Generate Initial Population

[ o(1,1), p.initialPopulationParameters ] = initPopFncDEV(...
    p.populationSize,...
	p.objectiveVars,...
    p.objectiveFrac,...
	p.minClusterSize,...
	p.sourceIndex,...
	p.destinIndex,...
	p.gridMask     );

%% Initialize Genetic Algorithm

i = 1; 
stop = 0;

while stop == 0

    selectionOutput = tournamentSelectionFnc(...
        o(i,1).population,...
        p.tournamentSize,...
        p.selectionProbability,...
        p.selectionType,...
        p.objectiveVars     );

    crossoverOutput = popCrossoverFnc(...
        selectionOutput,...
        p.sourceIndex,...
        p.destinIndex,...
        p.crossoverType,...
        p.gridMask          );

    o(i+1,1).population = popMutationFnc(...
        crossoverOutput,...
        p.gridMask,...
        p.mutationFraction,...
        p.mutationCount     );
    
    i = i+1;
    
    stop = 1;

end