%% Preliminaries

cd ~/Repositories/MOGADOR
run params.m

%% Initialize Ouput Parameters

o = cell(p.maxGenerations,2);

%% Simulate Objective Variables 

p.objectiveVars = simObjectivesFnc(...
    p.objectiveCount,...
    p.objectiveSimulationMean,...
	p.objectiveSimulationRange,...
	p.gridMask          );

%% Generate Initial Population

[ o{1,1}, p.initialPopulationParameters ] = initPopFncDEV(...
    p.populationSize,...
	p.objectiveVars,...
    p.objectiveFraction,...
	p.minimumClusterSize,...
	p.sourceIndex,...
	p.destinIndex,...
	p.gridMask          );

%% Evaluate Initial Population Fitness Parameters

o{1,2} = popFitnessFnc(...
    o{1,1},...
    p.objectiveVars,...
    p.gridMask          );

%% Execute MOGADOR

i = 1; 
stop = 0;

while stop == 0
    
    if i == p.maxGenerations
        
        break;
        
    end
    
    currentPopulation = o{i,1};

    selection = tournamentSelectionFnc(...
        currentPopulation,...
        p.tournamentSize,...
        p.selectionProbability,...
        p.selectionType,...
        p.objectiveVars     );

    crossover = popCrossoverFnc(...
        selection,...
        p.sourceIndex,...
        p.destinIndex,...
        p.crossoverType,...
        p.gridMask          );

    mutation = popMutationFnc(...
        crossover,...
        p.gridMask,...
        p.mutationFraction,...
        p.mutationCount     );
    
    fitness = popFitnessFnc(...
        mutation,...
        p.objetiveVars      );
    
    o{i+1,1} = mutation;
    o{i+1,2} = fitness;
    
    averageFitness
    
    i = i+1;
    
    % Insert Convergence IF/THEN Stopping Condition Here
    
end

%% Parse Output
