function [ objectiveVars ] = simObjectivesFnc( simObjCount, simMean,...
                                simRange, gridMask )
                            
% simObjectivesFnc.m This function generates 2-D random simulations of 
% problem objective surfaces by simulating values from a multivariate
% Gaussian distribution using a user specified distance based covariance
% structure.
% 
%
% DESCRIPTION:
%
%   Function to generate 2-D random simulations of problem objective 
%   surfaces which are sampled from multivariate Gaussian distribution with
%   a covariance structure specified by the user
% 
%   Warning: minimal error checking is performed.
%
% SYNTAX:
%
%   [ objectiveVars ] =  simObjectivesFnc(  simObjCount, simMean,...
%                           simRange, gridMask )
%
% INPUTS:
%
%   simObjCount =   [g] scalar value indicating the number of simulated 
%                   objective realizations to be generate by the function
%
%   simMean =       [d] scalar value indicating the mean objective value to
%                   be exhibited by the simulated objective realizations 
%                   generated by the function
%
%   simRange =      [h] scalar value indicating the distance range to be
%                   used to generate the covariance structure used in the 
%                   simulation process
%
%   gridMask =      [g x f] binary array with valid pathway grid cells 
%                   labeled as ones and invalid pathway grid cells labeled 
%                   as NaN placeholders
%
% OUTPUTS:
%
%   objectiveVars = [r x s] array in which each column corresponds to a
%                   decision variable (s) and in which each row (r) 
%                   corresponds to a spatially referenced grid cell value 
%                   (covering the entire search domain)
%
% EXAMPLES:
%
%   Example 1 =
%
%                   gridMask = zeros(100); 
%                   gridMask(1,:) = nan; 
%                   gridMask(:,1) = nan; 
%                   gridMask(end,:) = nan; 
%                   gridMask(:,end) = nan;
%
%                   simObjCount = 3;
%                   simMean = 5;
%                   simRange = 100;
%
%                   [objectiveVars] = simObjectivesFnc(simObjCount,...
%                                       simMean,simRange,gridMask);
%
% CREDITS:
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%                                                                      %%
%%%                          Eric Daniel Fournier                        %%
%%%                  Bren School of Environmental Science                %%
%%%               University of California Santa Barbara                 %%
%%%                            September 2013                            %%
%%%                                                                      %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Parse Inputs

p = inputParser;

addRequired(p,'nargin',@(x) x == 4);
addRequired(p,'simObjCount',@(x) isnumeric(x) && isscalar(x) &&...
    ~isempty(x));
addRequired(p,'simMean',@(x) isnumeric(x) && isscalar(x) && ~isempty(x));
addRequired(p,'simRange',@(x) isnumeric(x) && isscalar(x) && ~isempty(x));
addRequired(p,'gridMask',@(x) isnumeric(x) && ismatrix(x) && ~isempty(x));

parse(p,nargin,simObjCount,simMean,simRange,gridMask);

%% Iteration Parameters

n = size(gridMask,1);
m = size(gridMask,2);
p = n*m;
xSize = 1;
ySize = 1;
xMin = 0.5;
yMin = 0.5;
gridSpecs = [n xMin xSize; m yMin ySize];
xy = makegrid(gridSpecs);

%% Build Covariance Model

c = exp(-3*squareform(pdist(xy))/simRange);

%% Simulate Objective Realizations

s = repmat(simMean, [n*m 1]);
yy = mvnrnd(s,c,simObjCount)';

%% Generate Final Outputs

mask = reshape(gridMask,p,1);
nanTest = ~isnan(mask);
mask(nanTest) = 1;
mask = repmat(mask,1,simObjCount);
objectiveVars = yy.*mask;

end